name: Codecov Demo

on:
  push:
    branches:
main
  pull_request:
    branches:
main

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Test
        uses: actions/checkout@v1
      - name: Build and Test
        run:  xcodebuild test -project TallestTowers.xcodeproj -scheme TallestTowers -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.3' build test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3